Update

diff --git a/deploy.yml b/deploy.yml
--- a/deploy.yml
+++ b/deploy.yml
@@ -16,7 +16,6 @@ phases:
     commands:
       # Running Terraform commands
       - echo Build started on `date`
-      - ls -al
       - cd infrastructure
       - echo Preparing for tf init
       - rm -f .terraform.lock.hcl
@@ -36,13 +35,33 @@ phases:
       - echo "Running Trivy scan..."
       - trivy config tfplan | tee /tmp/trivy_output.txt
 
-      # Check if "Failures" exists in the output and stop deployment if found
-      - if [ ! -f /tmp/trivy_output.txt ]; then echo "Trivy output file missing!"; exit 1; fi
+      # Check if "Failures" exists in the Trivy output and stop deployment if found
+      - if [ ! -f /tmp/trivy_output.txt ]; then echo "Trivy output file missing!"; fi
       - if grep -i "Failures" /tmp/trivy_output.txt; then
-          echo "Trivy found errors! Stopping deployment.";
+          echo "Trivy found errors! Please fix the errors provided, and run the pipeline again.";
           exit 1;
         fi
       - echo DONE
+
+      # Installing & running Terrascan
+      - echo "Installing Terrascan..."
+      - wget -q https://github.com/tenable/terrascan/releases/download/v1.19.9/terrascan_1.19.9_Linux_x86_64.tar.gz
+      - tar -xzf terrascan_1.19.9_Linux_x86_64.tar.gz
+      - mv terrascan /usr/local/bin/
+      - rm terrascan_1.19.9_Linux_x86_64.tar.gz
+      - terrascan version
+      - echo "Running Terrascan scan..."
+      - terrascan scan | tee /tmp/terrascan_output.txt
+
+      # Check if "Scan Errors" exists in the Terrascan output and stop deployment if found
+      - if [ ! -f /tmp/terrascan_output.txt ]; then echo "Terrascan output file missing!"; fi
+      - if grep -i "Scan Errors" /tmp/terrascan_output.txt; then
+          echo "Terrascan found errors! Please fix the errors provided, and run the pipeline again.";
+          exit 1;
+        fi
+      - echo DONE
+
+      
 
 artifacts:
   files: ["**/*"]
